name: CI

on:
  push:
    branches: [ 'ready/**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Integrate
      run: |
        git rebase master
        git checkout master
        git merge ${GITHUB_REF##*/}

    - name: Build
      run: ./gradlew build
      
    - name: Publish
      run: git push origin master
