name: CI

on:
  push:
    branches: [ 'ready/**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch master
      run: git fetch origin master

    - name: Log 1
      run: git log --all --graph --oneline --decorate

    - name: Rebase on master
      run: git rebase origin/master

    - name: Log 2
      run: git log --all --graph --oneline --decorate

    - name: Merge into master
      run: |
        git checkout -b master origin/master
        git merge ${GITHUB_REF}

    - name: Log 2
      run: git log --all --graph --oneline --decorate

    - name: Build
      run: ./gradlew build

    - name: Publish
      run: git push origin master
